### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by OcrSu** [MehVahdJukaar/Supplementaries#101]
here is the log : https://pastebin.ubuntu.com/p/SRVBwKf53R/
java11
OS:forge2.2

**Comment by DPurple** [comment]
Vector3d#zRot was marked as @OnlyIn(Dist.CLIENT)
which not exists in server

**Comment by MehVahdJukaar** [comment]
So first of all how did you get that arrow? I haven't added it yet because it was still buggy and not ready.
Also yes code stripping mojang does is retarded and many times doesn't even make sense. I wish there was some ide or gradle task that would warn when one was using some of those stripped methods on the wrong side

**Comment by OcrSu** [comment]
> So first of all did you get that arrow with a command? I haven't added it yet because it was still buggy and not ready.
> Also yes code stripping mojang does is retarded and many times doesn't even make sense. I wish there was some ide or gradle task that would warn when one was using some of those stripped methods on the wrong side

Neither my players nor I got arrows by command.
I'm not sure, how that thing appeared
We've made some defenses on the forge and are looking forward to the next version update.
