### ISSUE TITLE
[❓]: Worst April Fools Trick EVER

### ISSUE THREAD

**Issue by alliraine** [MehVahdJukaar/Supplementaries#1014]
### Your Question

Do you really think making people's games crash on April 1st was a good trick?

### Detail

I seriously hope that this was just some really weird bug and not done purposely to "be funny". As someone who has spent an incredible amount of time in the Minecraft community this was so infuriating. Not funny at all.

**Comment by macks2008** [comment]
why would you assume that the crash was the intended effect? Secondly, it seems rather likely it was NOT intentional, since the error was a NullPointerException, one of the most common exceptions you can get, easily by accident, in Java.
I think it was trying to find it texture that wasn't available for some reason. and my understanding is that it's already been fixed in the latest version, so...

**Comment by macks2008** [comment]
this is also the second time I've seen an April fools Easter egg cause crashes. The same thing happened last year with better than llamas, except that happened during init. While, again, I don't think this was intentional, it does make me wonder how thoroughly ya'll tested your Easter egg logic. Either set your system time or coerce the branch to be true, you know?

**Comment by MehVahdJukaar** [comment]
I have received around hundreds of this same report not kidding. People not even checking if there's already an issue opened for this.
If you think the crash was deliberate seriously find something better to do. 
This issue was a fabric only thing which was  fixed 2 days ago yet so many reported despite there being many issues with the same name active and despite the guideline on GitHub saying to check if your mods were updated never did
