### ISSUE TITLE
Compat; Bypassing Forge Event callbacks 

### ISSUE THREAD

**Issue by simibubi** [MehVahdJukaar/Supplementaries#104]
Greetings o7
We found a funky interaction:

Create subscribes to forge's interact events for in-world filter slots.
Supplementaries subscribes to the same event in order to handle the placeable sticks feature.

Its handler's high priority setting causes it to run first: <https://github.com/MehVahdJukaar/Supplementaries/blob/83126033b46e2c9d89eb769cf95ae486afb02812/src/main/java/net/mehvahdjukaar/supplementaries/events/ServerEvents.java#L46>
The sticks' placement feature skips interaction event handling by asking the blockstate for an action result directly <https://github.com/MehVahdJukaar/Supplementaries/blob/83126033b46e2c9d89eb769cf95ae486afb02812/src/main/java/net/mehvahdjukaar/supplementaries/events/ItemSOverrideHandler.java#L415>

Therefore, if a block returns != pass, all modded interact handlers that do not claim 'highest' priorities are skipped.
Ultimately this means any item made placeable in new ways will not be accepted as filters on a handful of Create blocks such as the funnel.

My suggestion would be to consider the new placement options a low or lowest priority handler, as sneaking should bypass most interaction handlers added by other mods.
Feel free to ask if you need more details, or to close if you consider this a non-issue.

Cheers!

**Comment by MehVahdJukaar** [comment]
oh that's a good point. I'll try fix it accordingly

**Comment by MehVahdJukaar** [comment]
Thanks for the report, I've set it on low priority and tested it with a basin and works fine. Having lower priority makes sense since block placement actions like I am doing should come after other block interactions.

Oh since we are talking about placeable sticks I wanted to take the opportunity to suggest also taking a look at https://github.com/Creators-of-Create/Create/issues/2149, which sparks from the need for my placeable sticks to be viewed as 3 stick item instead of their block item. I know you guys have so many issues there so that might have gone under the radar. It's nothing major tho so no hurry :)

Cheers

**Comment by simibubi** [comment]
Will do, thanks 👍
