### ISSUE TITLE
Add HYWLA/Jade/One Probe Integration to Item Shelf

### ISSUE THREAD

**Issue by xtrial** [MehVahdJukaar/Supplementaries#11]
Can you add integration to HYWLA to display informations about item on the shelf, like showing what enchantments on the item, or anything informative like that?

**Comment by MehVahdJukaar** [comment]
the shelf is an inventory like many others and it works just fine with the one probe. I have no idea how HYWLA works but I've tried looking at other vanilla inventory and, as opposed to the one probe, it didn't show their content.

**Comment by xtrial** [comment]
After some testing, it does display the item. However, you need to hover the cursor at the top side of the shelf so that the item will be displayed by hywla/jade/one probe and this is a problem if you put the shelf higher than player's head.

Maybe, make the displayed item selectable, but i guess that will be hard.
Or display the information when hovering at the block (item shelf) itself?

**Comment by MehVahdJukaar** [comment]
oh yeah I remember. The way those two mods work it kind of clever since they do display the item same item that you would get when middle clicking said block, hence why they show "lantern" or "pot" when hovering over my wall lanterns and hanging pots even if they are two different blocks. Of course it is showing the item only when you hover on top because that's how I coded it. I wanted that if you middle clicked the block it gave you the shelf and if you were to click the top part where the block is it gives you the displayed item. pedestals work the same

**Comment by MehVahdJukaar** [comment]
I'm not sure if one can edit what item is shown by those two mod since they rely on the pick item code. I'm not sure one would benefit by having the creative pick item feature removed too but I guess I could add a config options that disables them all and always shows the displayed item

**Comment by MehVahdJukaar** [comment]
this would only cunt for HWYLA because as far as I've seen the one probe shows the content of a block below the actual pick bock name in a blue box and that seems to work with any block that has an inventory so with that mod it works perfectly. If I were to make it show the dislayed item with the one probe installed it would show it twice, one in the block name and another in the block content below

**Comment by xtrial** [comment]
Welp, to think that this will be an edge case for HYWLA or Jade.

> I'm not sure if one can edit what item is shown by those two mod since they rely on the pick item code. I'm not sure one would benefit by having the creative pick item feature removed too but I guess I could add a config options that disables them all and always shows the displayed item

👍
