### ISSUE TITLE
Can't craft spring/piston launcher 

### ISSUE THREAD

**Issue by ChildishGiant** [MehVahdJukaar/Supplementaries#114]
It also doesn't show up in JEI.
![2021-09-21_18 11 10](https://user-images.githubusercontent.com/13716824/134216464-bd0b0843-d5ed-4a55-9779-7635e3428651.png)
It is however in the creative inventory

**Comment by MehVahdJukaar** [comment]
I can't replicate this but I see you are not using the latest version. I don't think it would make a difference since I didn't change it but still try using that. Maybe you are using a modpack that has disabled its recipe and not disabled it via configs which would have disabled its recipe & hidden it from jei

**Comment by ChildishGiant** [comment]
Ah, sorry for that.
