### ISSUE TITLE
[Accessibility] Clock Block spams subtitles with "Note Block plays"

### ISSUE THREAD

**Issue by Vaelzan** [MehVahdJukaar/Supplementaries#13]
I'm guessing you have implemented the ticking of the clock by just triggering a vanilla note block sound each second, but this causes two problems for those who play with subtitles on:

1. The wrong subtitle displays, since the Clock Block isn't a Note Block.
2. The subtitles are constantly showing that message if in the area, causing more useful subtitles to be drowned out, and taking up screen space needlessly.

I haven't checked how hard it would be to play a sound without also showing a subtitle, but a ticking of a clock is probably fine to leave out of the subtitles section entirely, since it's more an ambient sound.

**Comment by MehVahdJukaar** [comment]
Oh I didn't think about this. I'm going to disable the ticking altogether since I didn't really like that sound anyways and I was going to add its own unique sound anyways. Of I probably would have given it correct subtitles but now that you mention it, it does seem like it would spam them quite a bit so I'll probably give it no subtitles at all
