### ISSUE TITLE
Most mobs (including vanilla ones) display weirdly while inside a Cage or Jar

### ISSUE THREAD

**Issue by Brun333rp** [MehVahdJukaar/Supplementaries#15]
![2021-02-01_15 45 10](https://user-images.githubusercontent.com/77504298/106517241-fdcf9f80-64b6-11eb-89aa-891088ca814b.png)
Many baby animals display extremely small. Note that the pig's eyes are not even appearing

![2021-02-01_15 10 38](https://user-images.githubusercontent.com/77504298/106514461-07ef9f00-64b3-11eb-911c-b18874672706.png)
A big difference between caged baby Hoglins and baby Zoglins

![2021-02-01_15 13 47](https://user-images.githubusercontent.com/77504298/106514649-4b4a0d80-64b3-11eb-8a3b-bfdca398de1e.png)
How their item forms look like

![2021-02-01_15 04 17](https://user-images.githubusercontent.com/77504298/106514735-674daf00-64b3-11eb-957c-b495690e3ad5.png)
How a Silverfish inside a Jar look, compared to other mobs

![2021-02-01_15 57 22](https://user-images.githubusercontent.com/77504298/106515403-6701e380-64b4-11eb-8335-3cfd4c6cea7a.png)
Some mobs might display with their heads out of Cages. From left to right: Ocelot, baby Wolf, Fox and baby Foxhound (from Quark);

![2021-02-01_15 20 05](https://user-images.githubusercontent.com/77504298/106515722-d37ce280-64b4-11eb-9e24-c7daaef9185d.png)
Baby Panda compared to caged baby Panda

![2021-02-01_15 17 50](https://user-images.githubusercontent.com/77504298/106519307-d9c18d80-64b9-11eb-88c0-7f82ce139882.png)
Baby Polar Bear compared it's caged counterpart

![2021-02-01_18 09 08](https://user-images.githubusercontent.com/77504298/106518460-b0543200-64b8-11eb-91cd-93bccc74c743.png)
How most of Alex's Mobs baby mobs look, compared to their caged counterparts. Note that it might affects other mobs as well, these are the ones I have added. Also, baby Warped Toads and baby Endergrades look normal.

![2021-02-01_15 24 10](https://user-images.githubusercontent.com/77504298/106515302-3c178f80-64b4-11eb-8aa8-f95f97848ae1.png)
Separate picture of baby Crocodile for better comparison

**Comment by MehVahdJukaar** [comment]
so basically to fit mobs inside a jar or cage I have to scale them. The only way for me to do it is by using their hitbox. Try pressing f3+b and you'll see that they all have their hitbox that precisely matches one of the two cage dimension. If a mob actual models shape doesn't match its hitbox only think I can do is add special individual cases for them. I have already a few for vanilla mobs but of course I can't add a special case for all modded mobs. Baby mobs are one of the main culprit here since they like to have a reduced hitbox but still use the adult head that potrudes way outside said hitbox. That can only be solved through special cases though since some baby have their head on the top others on the front so I can't just scale all babies down cause for example a baby zombie would fit with current dimensions inside a cage while a hoglin will not. I do have a solution planned for this: it will basically bring that part of the code onto the configs file where one will be able to tweak a mob special parameter (basically two x and y values that will be added to its actual hitbox when calculating its scaling factor). I still have to figure out how to do that though

**Comment by Brun333rp** [comment]
yes, I undestand that. didn't wanted to sound rude, sorry if I did so

**Comment by MehVahdJukaar** [comment]
no worries. I had plans to implement that solution since I knew that was an issue. I'll get to it when I'll learn how to add such a complex data structure to the config

**Comment by MehVahdJukaar** [comment]
"fix" will be coming next update. you'll be able to edit each mob size trough configs
