### ISSUE TITLE
[1.16.5] Iron Gate and Netherite Door don't work with Coupled-Door-Opening Mod(s)

### ISSUE THREAD

**Issue by IdrisQe** [MehVahdJukaar/Supplementaries#155]
The Iron Gate and Netherite Door don't correctly open both doors when right clicking with [Double Doors](https://www.curseforge.com/minecraft/mc-mods/double-doors) despite every other modded door and gate I've seen working fine with it. Not sure why, honestly.

**Comment by MehVahdJukaar** [comment]
it's because they use a different door opening mechanic. and are not just another oak door retexture. Netherite doors have to check if they CAN be opened by checking it the player has the correct key so if two with different keys assigned to eachother were placed next to one another they should not be openable at once if the player did not have both keys. Having said that I've already added a builtin system that kicks in when quark is installed since it has that double door feature and it's off by default (not cause I'm using its code but for consistency). I don't know why anybody would use anything else other that Quark (since most people have that installed already) but I can always add a check to turn it on if that other mod is installed too.

**Comment by IdrisQe** [comment]
Oh, I had no idea Netherite Doors even had special functionality since they seemed to just work with normal right clicks for me, so I never really questioned it!

(But yeah, honestly I'm not even entirely sure why I'm not using Quark. It wasn't in the base modpack I'm using and so I guess I just didn't want to add anything as substantial as Quark to it so I wouldn't break anything.)

**Comment by MehVahdJukaar** [comment]
oh also to add to this I have a config option for double gate opening that you can turn on
