### ISSUE TITLE
[feature request] additional sack functionality

### ISSUE THREAD

**Issue by esotericist** [MehVahdJukaar/Supplementaries#160]
it'd be nice if we could dye sacks, to help distinguish between them (in case you own a bunch, and want to have specific ones for specific purposes)

it would also be nice if we could pull from sacks in-inventory like we can pull from bundles, instead of having to place the sack down every time.

**Comment by MehVahdJukaar** [comment]
I don't relally like the first suggestions since that would make them even more similar to shulker boxes. Also the fact that you can only really carry 2 at a time would make the colorcoding not really necessary.
For the second suggestion you can already do just that.

**Comment by esotericist** [comment]
> I don't relally like the first suggestions since that would make them even more similar to shulker boxes. Also the fact that you can only really carry 2 at a time would make the colorcoding not really necessary. 

i think i was under the impression of 'low tier/early game shulker box' was the intent. for my purposes, shulkers are so far past where i normally play that they might as well be unobtainium, so a simpler/less powerful alternative analog was highly appealing.

as for the utility: i have been in the habit of putting sacks down in my base, filling them with stuff (such as from farming or processing loot), then picking up specific ones before heading to e.g. specific villages to trade. so i thought color would help. 

> For the second suggestion you can already do just that.

how? i right click on the sack with nothing in my cursor, it picks up the sack. i right click on an empty tile with the sack on my cursor, it puts down the sack. bundles work fine for me.

this is forge 1.18.1-39.0.5, and suplementaries-1.18-1.0.7.

**Comment by MehVahdJukaar** [comment]
hmm that's odd. I might have accidentally disabled that in latest release but that was one of the feature that I added.  I'll fix it on next release. they will work like bundles + have the bundle like overlay if quark is installed (cause I like it better than the bundle one and I've also customized it)
For colored sacks I don't think I'll add them. Not really a fan of adding many colored variants to a block and I don't even think they would look that nice colored. Only thing that would look good is if they had the red string change color but that is so minor it would be barely noticeable. If you are having extensive use of sacks also remember that you can increase their capacity in the configs so that might be handy.

**Comment by esotericist** [comment]
@MehVahdJukaar were you unable to get the sack bundle behavior restored? there's been a few releases since then, but that still isn't present, so i'm unsure why you closed this issue entirely.

**Comment by MehVahdJukaar** [comment]
So I closed this because I fixed that sack issue. I just checked and both clicking on an item  with a sack and vice versa add the item to the sack itself so it's all working as intented. Maybe you are referring to that other abilities bundles have where you can drop stuff out by clicking it. I didn't add that one cause I didn't want then to be too similar. Of course I'm referring to the current 1.18 version since I'm not supporting old ones anymore

**Comment by esotericist** [comment]
my specific complaint from the start was that I wanted to be able to remove items from the sack as easily as I put them in. having to place the sack down, access it as a container, then go to the trouble of breaking the sack, seems absolutely incoherent in the face of being able to trivially add items to it.

at that point why allow adding items?

**Comment by MehVahdJukaar** [comment]
I see your point, I misunderstood at the start then. I didn't add that feature in from the start since I wanted them to be consistent to what quark does to shulker boxes where they too can only have stuff put in and not taken out. I'll probably add this in next time I get the chance since it's still nice to have and maybe have a config to turn it iff

**Comment by drakray** [comment]
Hi there, sorry to hitch on this, but I too wanted to ask about colored sack, and after ready through your explanation, I think, if you would add them, maybe just but a kind of colored belt around the belly of the sack, since indeed the string would be unnoticable/useless, and a colored jute bag would look wierd

As for the ability to open the sack from hand to get something inside, is this still a planned feature?, On my server I mainly use Sack to store food and potion, being able to quickly get some without placing the Sack down would be very nice

Thank you for you good work :D
