### ISSUE TITLE
High TPS jitter on supplementaries-1.18.1-1.1.2

### ISSUE THREAD

**Issue by ohnx** [MehVahdJukaar/Supplementaries#172]
I run an "All The Mods 7" server and Supplementaries seems to be one of the mods in this pack. Recently, I've noticed some high jitter in the TPS on the server.

Version info:

Forge: 39.0.9
Minecraft: 1.18.1
Supplementaries: 1.1.2

Spark profile available here: https://spark.lucko.me/XKl7UbT7MW

Reading the trace, it seems that the cause of this issue is very similar to another one that I encountered with a different mod, tracked here: https://github.com/Ellpeck/NaturesAura/issues/235

I guess `level.getChunkSource()` takes a long time to run sometimes (maybe it's doing a disk read?), and that results in a very high TPS in those cases.

The patch that that mod-maker used is this: https://github.com/Ellpeck/NaturesAura/compare/13e6307921a741fd71ed1048151053bfd17579bf...87d080416da4308c1ed22f0518a3d027fdb137a8

**Comment by MehVahdJukaar** [comment]
Can you try that again but using the latest version?

**Comment by dumpsters** [comment]
I've also been having terrible performance with Supplementaries on my server.
Did two spark reports, one with it [enabled](https://spark.lucko.me/d5yuorAcwV) and another with it [disabled](https://spark.lucko.me/8pMikEnTuV).
Both tests on different brand new worlds, as soon as I connected to the server I started the profiler and started running in a random direction to keep generating things.

The person who analyzed the first report said the following:
> supplementaries is having a threadlock
> waiting for something to happen and blocking things
> must be running on a different thread, blocking the main thread
and after analyzing the second report:
> yep something from that is taking a long time to execute something

Version tested:
supplementaries-1.18.1-1.1.7.jar with selene-1.18-1.11.jar

**Comment by MehVahdJukaar** [comment]
ok so could you put me in contact with whoever analized that? Usually the whole point to run stuff on a diff thread is not to hang up the main thread so that doesn't make much sense to me. From what I can see by searching that profile is that most of that stuff can be lead back to my chunk watch event, a recent addition that was needed to sync capabilities. I'll investigate. Could you confirm that the lag you saw indeed comes from that ServerEvents.onPlayerStartTracking? I'm not that experienced with reading those profiles so do tell me if there are other calls worth looking at

**Comment by MehVahdJukaar** [comment]
maybe I identified the issue. that method itself is kind of slow but shouldn't slow as much. I was indeed asking the server to run a task after a tick but it was instead making it wait one, at least that's my hypothesis

**Comment by dumpsters** [comment]
> ok so could you put me in contact with whoever analized that?

I can't, join the spark discord and search for that report, you'll find the guy analyzed it. As far as why that piece of code is being a problem I couldn't tell you because I never really studied Java.

> Could you confirm that the lag you saw indeed comes from that ServerEvents.onPlayerStartTracking?

The only thing I can confirm is the server running much better after disabling the mod not only during chunk loading but also overall, less tick delays and dramatically less "rollbacks".

**Comment by MehVahdJukaar** [comment]
I found a different way to handle that syncing code. I'll upload soon so would be cool if you could compare it

**Comment by dumpsters** [comment]
Tested `supplementaries-1.18.1-1.1.8.jar` and it looks promising, "rolled back" only once while exploring a [nice bit](https://i.imgur.com/zZzafN3.jpg) of the fresh world (probably because of other mod) and in the [spark report](https://spark.lucko.me/Wo3KqdsBV8) you can see by clicking the eye icon how significantly lower the time (?) taken by the mod is.
Seems good so far, if I notice anything weird I'll let you know.

**Comment by MehVahdJukaar** [comment]
Awesome, so it was indeed that weird cap synching I had. Let me know if you find more even slight performance issues. I rarely perform those kind of tests cause I dont have a server so stuff like that can pass under the radar
