### ISSUE TITLE
[Suggestion] Multiple candles on one candle holder (same method as vanilla sea pickles).

### ISSUE THREAD

**Issue by Vaelzan** [MehVahdJukaar/Supplementaries#19]
In vanilla Minecraft, you can right-click an existing sea pickle block and it will grow to contain an additional sea pickle, for a maximum of four. The light-level increases each time this is done. Similarly, the 1.17 candles are going to act in the same way, where an additional candle is placed every time you right-click on the same block.

Along the same lines, it could be nice to have candle holders "grow" to hold multiple candles in the same block-space, but probably to a maximum of three (so it looks essentially like an iron version of a wall-mounted candelabra after right-clicking with candle holders three times).

**Comment by MehVahdJukaar** [comment]
I was considering adding this since when 1.17 comes out candle holders will probably be treated like wall lanterns, meaning they will not exist in item form and will only be placed when one would place a vanilla candle on a wall, basically allowing vanilla candles to have more states. Having said that It would infact make sense for them to be able to get placed like candles to, up to 4 in a block. Only think is that I'm not sure how that would look. Would it create 4 separate candle holders? would it create a bigger one? Your candelabra idea kind of works but it would make the actual candelabra kind of redundand and if I'm adding this it will be up to 4 like normal candles. Let me know what you think and keep up the good word with the modpack :D

**Comment by Vaelzan** [comment]
If it were my mod, I would just merge candle holders and candelabras (which would essentially result in having a single one placed look the same as a normal candle holder, and while it would be messy with existing Item IDs, would also result in having all the same options available to iron, silver, and gold materials).

If intending to increase it to four, when wall mounting I would have them laid out in a T shape, with three close to the wall and one sticking out. Perhaps have the middle-back one raised above the others too with a higher support?

Ultimately it's completely up to you, it's just something that I thought of while testing out some existing lighting options.

**Comment by MehVahdJukaar** [comment]
Well after more than a year i can finally close this
