### ISSUE TITLE
Flax not compatibile with Quark's "simple farming" (1.16)

### ISSUE THREAD

**Issue by Toma400** [MehVahdJukaar/Supplementaries#195]
Quark's one of the features is "simple farming" which means that you can right-click on plant and it will be both gathered & planted instantly, without need to do it by vanilla two-step way (breaking and planting).
Although Farmer's Delight use this feature, unfortunately Supplementaries Flax not, which means I need to break flax and plant it again separately, even with this feature being turned on.

It's minor inconvenience, but reporting it here just because it would be nice touch. I play 1.16 Forge, version of Supplementaries 0.18.2.

**Comment by MehVahdJukaar** [comment]
I can't replicate this. I have to say that I have both FD and quark on my dev environment but clicking with bonemeal, flax seeds or an empty hand always results in the flax plant being broken and replanted. Maybe it's a 1.16 only issue and I'm not sure if I'll be updating that anymore

**Comment by MehVahdJukaar** [comment]
So I also tested it in 1.16 and could replicate it there too (but might have been cause I already patched it in some indev version before). I also added a feature that allows to click on the upper stage to harvest it (or act as if the lower was clicked) since before only clicking the lower stage would work. Should work
