### ISSUE TITLE
[Suggestion] Snow on every block!

### ISSUE THREAD

**Issue by Matthysse** [MehVahdJukaar/Supplementaries#2]
Hello!
We are in winter, and I feel like there is something missing in Minecraft: snow on every block!
I mean by that that snow would land on stairs, slabs, walls, fences and fencegates. That would be awesome and would greatly improve winter villages!
It would work just like that: just like for normal blocks, the snow layer would be a block above the slab for example, but the model of the snow would be just on the slab itself, with the possibility to add more layers. The snow layer would check for the tag that the block is a stair/slab/fence/fencegate, so that it would be compatible with modded blocks!
With that you could add natural snow accumulation, so that we could see naturally why not up to layers of snow on the ground.
If you want to know how it would work in practice, there was a perfect mod in  1.10.2 called ShiftedSnow : https://www.curseforge.com/minecraft/mc-mods/shiftedsnow
As it does change the world a lot, this feature could be removable in the config file, as well as with the configuration of the maximum heights of layers that can accumulate naturally.
I created all the models with the snow texture and with the 8 layers for all those blocks I mentioned, so if you want them, I can give you them!

I know there is a mod called SnowRealMagic that does that, but it creates a block for every block covered in snow, so if you directly remove the mod, all the snow-covered blocks disappear.

**Comment by MehVahdJukaar** [comment]
I didn't realize SnowRealMagic had them implemented that way since I've only seen it in action in screenshots. If that's the case I could indeed make something of the sort even if it probably could use a separate mod. There are however a couple of issues that I can see: blocks that don't have an tall hitbox could have a problem since they would basically have an invisible block on top of them. Also to break the snow layer you would have to click on the block above the slab and that means that it would have to have an hitbox and be invisible at the same time which is probably why snow real magic implemented it that way. I was hoping that 1.17 would add some sort or "snowlogging" to all blocks but apparently that won't be happening. I'm guessing the ideal solution would be infact to add such snowlogging mechanic to all the related vanilla classes but that could potentially cause alot of incompatibility and I actually have no idea of how to do that since it's not as simple as adding a block state to all of them. So in short SnowReal magic probably adds this feature in a nicer way, even if that means that they do have to create a special case for every single modded stair and fence and they disappear once you remove the mod.

**Comment by Matthysse** [comment]
Yeah but this causes other problems like the fact that it's not really snow on them, so if you use Serene Seasons it doesn't melt. I think having an invisible block above isn't a problem. People rarely want to place a decoration or block on top of a snow layer, and the bounding box can be in the block under, (ShiftedSnow made it), so there would be no confusion :D
