### ISSUE TITLE
Compatibility issue with quark in 1.18.1

### ISSUE THREAD

**Issue by RageLeague** [MehVahdJukaar/Supplementaries#206]
While playing with quark and supplementaries together in 1.18.1, I found two compatibility issues that may or may not be related to this mod.

First, when the double door opening is enabled, right clicking the door with a stick will cause only one door to open. This issue doesn't seem to occur with any other item that I tested except sticks, so I assume that might be due to the fact that this mod allows sticks to be placed in the world.

Second, the xp bottling doesn't seem to be working with quark oddities' matrix enchantment table system. The matrix enchantment table uses a new block ID separated from the vanilla enchantment table, so I'm assuming that's why it's not working, but it would be nice if the xp bottling works with enchantment tables from other mods. Not sure what is the best way to achieve this, though.

**Comment by MehVahdJukaar** [comment]
with the new system I have in 1.2.2 I've gotten rid of some of the issue with the old placeable block system. It's only partial tho and it doesn't include modded stuff or wall lanterns which can still bypass forge events when clicked on a block(since they themselves are using a forge event to be placed)
For the matrix echanting table I'm not sure why its not working and infact I remember it working 6 months ago when I played with quark oddities. thing is they use the same block class with a differen tile entity and my system should have covered it. I'll look in to it for now I'll look into it

**Comment by MehVahdJukaar** [comment]
Just tested and it does work with matrix enchanter so I'll close this
