### ISSUE TITLE
[1.18.2] Crash on server startup with Snowy Spirit, possbily relating to the new Selene lib file

### ISSUE THREAD

**Issue by BugmanBugman** [MehVahdJukaar/Supplementaries#222]
https://gist.github.com/BugmanBugman/e307d943b3e8b403f69e76f645a05db8

**Comment by MehVahdJukaar** [comment]
this is due to a problem with blueprint and the newest forge version. As far as I can tell the issue is entirely on their side and it's related to one of their mixins failing to apply. I've been geteting a storm of reports of this just cause it blames my stuff since i'm the first mod that loads those classes and as soon as I do they crash since they have that failed mixin

**Comment by MehVahdJukaar** [comment]
https://github.com/team-abnormals/blueprint/issues/152
