### ISSUE TITLE
[enhancement] can you add own candle ?

### ISSUE THREAD

**Issue by AlleCraft-alterego** [MehVahdJukaar/Supplementaries#30]
can you add own candle ?
for your recipe requirement candle

and.... why cannot be placed on the floor candle holder ? please add this placement

**Comment by MehVahdJukaar** [comment]
there are already way too many mods that add candle. Adding yet another one that would basically do the same thing that they do won't be something that I would want to do. They were supposed to act as wall candles for 1.17 candles but that version is taking ages to get released so I might make them placeable in the ground. Only problem I see with that is that they will be deleted when 1.17 does come out since then they will work as wall lanterns but for candles

**Comment by AlleCraft-alterego** [comment]
i have ask to add candle for remove dependies from buzzier bees or quark for candle

**Comment by MehVahdJukaar** [comment]
thing is they work even without. The default recipe uses torches. I might add one that uses bee hive and string too

**Comment by MehVahdJukaar** [comment]
Also recipes are super easy to tweak, either by hand through a datapack or with a mod like recipe tweaker

**Comment by AlleCraft-alterego** [comment]
yes, honey comb (and resourceful bees comb tag) and forge tag string is cool, torches recipe is...... poor

**Comment by AlleCraft-alterego** [comment]
can you add forbidden arcanus candle recipes compatibilities ?

**Comment by MehVahdJukaar** [comment]
I'll try to do that. Reason I used candles is that they were needed for candelabra since that one doesn't have room for honey comb and string it its recipe

**Comment by AlleCraft-alterego** [comment]
why don't you want to make some candle for your mod? it would be independent of other mods without recipe torches

**Comment by MehVahdJukaar** [comment]
why would I waste time make something that would get rendered useless when 1.17 comes out? I just don't get it :/

**Comment by AlleCraft-alterego** [comment]
because this version work on 1.16

**Comment by MehVahdJukaar** [comment]
I've added a better recipe for candle holders in 0.10.2. That's all I'm going to do. I don't want to waste time adding stuff that I would have to delete in a later version so that's that
