### ISSUE TITLE
Server crashed, I believe it was your mod

### ISSUE THREAD

**Issue by pjlasl** [MehVahdJukaar/Supplementaries#34]
https://pastebin.com/ttmmWEFp

**Comment by MehVahdJukaar** [comment]
well I have to thank my ide and forge for that one (also mine for blindly following the ide suggestion). Details are quite interesting: basically I was using projectile.getItem() by casting to IRenderAsItem instead of ProjectileItemEntity. My compiler which suggested that cast had no idea that that class was marked as client only by forge and it's actually removed on classloading (by forge I think) , so the correct cast was the other since they both have that method. I've corrected it now but It's still showing that up as strong cast warning lol. Also odd that it has only been reported now cause that code has been there for ages. Anyways I'll upload a new version very soon

**Comment by pjlasl** [comment]
It was the perfect storm apparently :).
Thanks for fixing so quickly!
