### ISSUE TITLE
[1.19.2] Crashing on world loading with Snow Under Trees mod installed.

### ISSUE THREAD

**Issue by murao-kun** [MehVahdJukaar/Supplementaries#351]
SnowRealMagic 5.0.2 causing crash on world loading when you have snow under trees mods installed along it.
[crash-2022-09-03_18.18.42-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/9482891/crash-2022-09-03_18.18.42-server.txt)

**Comment by OkinawaGaijin** [comment]
Sorry for chipping in albeit not being the dev, but aren't you on the wrong Github for this? Your crashlog mentions SnowUnderTrees and SereneSeasons, so I'd suspect a mod incompatibility between these two, especially since surely both handle snow blocks or layers in some way.

Why would Supplementaries be involved? It's not even showing up in the error related entries. I'm curious. I don't see any connection.

**Comment by murao-kun** [comment]
To be true I really don't get it myself but it is totally happening between Snow Real Magic and Snow Under Trees since when I am getting at least one of them, the issue is fixing itself.

**Comment by OkinawaGaijin** [comment]
Yeah, I get that.
But this repo is from MehVahdJukaar, who has nothing to do with any of these mods IIRC. He's developing Supplementaries.

SnowRealMagic is made by Snownee (https://github.com/Snownee/SnowRealMagic/)
SnowUnderTrees (Forge version) is made by bl4ckscor3 (https://github.com/bl4ckscor3/SnowUnderTrees)
SereneSeasons is made by Glitchfiend (https://github.com/Glitchfiend/SereneSeasons)

You posted this issue on the Supplementaries Github (https://github.com/MehVahdJukaar/Supplementaries)

**Comment by murao-kun** [comment]
F*ck I am dumb. I was sleepy and reported to wrong repo. 🤣

**Comment by murao-kun** [comment]
Tank you for pointing me, you right. I will move that to right location. I was bug testing newest update with Jukaar and closing the issues that he fixed. But I forgor to switch to right repo to report this one lmao. 🤣
