### ISSUE TITLE
Crash on game startup

### ISSUE THREAD

**Issue by pjlasl** [MehVahdJukaar/Supplementaries#38]
https://pastebin.com/ALvnGK28

**Comment by MehVahdJukaar** [comment]
Honestly I have no idea what's causing that. It's a mod incompatibility thing for sure since nobody else reported this before. Do you happen to have any mod that could modify the vanilla milk bucket?
I've made some changes to the code so next update it should at least fail silently without causing the game to crash but still I would like to get to the bottom of this

**Comment by scarha** [comment]
I am getting the same error if that helps and i have 232 other mods installed alongside.

**Comment by MehVahdJukaar** [comment]
Farmers delight is one of the mods that I even have installed on my dev environment and I've also made its bottles super compatibles with jars so that's definitely not it. As I've said I've put some error checking so next versions it shouldn't happen anymore and will simply fail to register that liquid but if some of you guys could find out with which mod it's conflicting you would be giving me a favor. To do so simply move half of you mods out of the mods folder and see if it boots. Then repeat until the other mod is found

**Comment by pjlasl** [comment]
Please note that happened only once, it isn't happening consistently. The only thing I can think of is I added a mod called "wooden buckets", but I have since removed it.

**Comment by MehVahdJukaar** [comment]
how odd

**Comment by pjlasl** [comment]
Here is another crash report. It revolves around Minecraft:milk...
https://paste.ee/p/8bWbu

**Comment by MehVahdJukaar** [comment]
got it. I think It's due to how forge handles milk bucket item: it registers a fluid for it but it doesn't initialize it and leaves it up to other mods to do so. I'll publish a fix soon

**Comment by pjlasl** [comment]
I can provide u with a list of mods I use, if that would be helpful

**Comment by MehVahdJukaar** [comment]
well not really needed. thing is forge had that thing with milk where mods can register stuff to it and it will automatically work with the milk bucket. There's probably a mod that adds milk fluid that initializes it to null, then my mod init gets called and then after that they initialize it. I've just added a null check and that's it

**Comment by MehVahdJukaar** [comment]
check out if this version works

**Comment by pjlasl** [comment]
sure. it usually occurs when i restart my server. I'll let you know if it happens again.

**Comment by pjlasl** [comment]
So far I have been using it since your update and after several daily restarts, I have not seen the issue come back.

**Comment by MehVahdJukaar** [comment]
great
