### ISSUE TITLE
croptopia plants in planter

### ISSUE THREAD

**Issue by superon** [MehVahdJukaar/Supplementaries#383]
i'd like to be able to add them with a datapack or something.. maybe a config option even, perhaps there is a way, i only tried searching for about 15 minutes and i'm not the best at discovering what im looking for...
i searched here too and only found croptopia issues relating to crashes, idk why that is, i feel like it certainly should be documented somewhere but posting incase it isn't.

**Comment by MehVahdJukaar** [comment]
Is this for fabric? Are you saying they don't work already? I'm sure forge one has universal plants and crop support

**Comment by superon** [comment]
sorry i should've posted version...
Croptopia-1.19.2-FORGE-2.1.0
i tried a whole bunch of the seeds

**Comment by MehVahdJukaar** [comment]
This is not on my end. I'm using forge IPlantable interface and IForgeBlock::canSustainPlantLife one which should guarantee that planteers support all plants (that impleent that) which for a forge mod should be all crops. I see that that is a cross loader mod so I suspect they are skipping over forge api causing poor compatibility such as this. That's also why I dont really like the multi loader environment since it leads to poor code like this and also what I try to avoid to the cost of longer dev times for my mods. Anyways this is an assumption but I'm quite certain of it. Note that adding a forge specific interface can be done with a mixin that target somebody's own class. I'll close this, you might want to report to them if you want it fixed
