### ISSUE TITLE
No Flax?

### ISSUE THREAD

**Issue by SirChamomile** [MehVahdJukaar/Supplementaries#40]
I can't seem to find flax anywhere. I looked in the code and it seems like it should be dropping from tall grass, but it's not working for me.

**Comment by MehVahdJukaar** [comment]
Yes I know, for some mysterious reason that part of the code isn't working. However instead of looking at the code you should have looked at the mod description because it's written there pretty clearly that for now you can find it in pillager outpost or sold by the wandering trader. Also I don't know how you didn't see this since this code is right next to the tall grass one

**Comment by SirChamomile** [comment]
Just an oversight on my part. I don't really know java, I was just trying to be informed by looking at the code and I missed the villager outpost line. A lot of mods don't utilize their curseforge page as well as you do, so I'm not used to looking there for information. Thanks for the response.

**Comment by MehVahdJukaar** [comment]
No problem. They are a bit rare now so just know that I might change where you get them in the near future
