### ISSUE TITLE
Illegitimate copy spam

### ISSUE THREAD

**Issue by CyberNewty** [MehVahdJukaar/Supplementaries#44]
Players in server are getting illegitimate copy message spam every world load, even with curseforge install.

**Comment by MehVahdJukaar** [comment]
That isn't supposed to happen since that check is entirely client sided so the server has nothing to do with it (this in the latest version 0.10.5 of course). It only check for the mod jar name and if you did modify it you can just easily remove it via the configs, as it itself states. When you say "players" it sounds like you're a server admin hand and I'm assuming you've had players report this to you but you didn't had this problem yourself. Are you sure they have downloaded it from there? If there's one thing I've learned when modding is not to trust players too much.

**Comment by CyberNewty** [comment]
If its based on the name, that's probably the issue.  I was assuming there was some internal hash check.  I have a pack batch file that orders and renames files for ease of configuration.  Ill push changes changes via config then.
