### ISSUE TITLE
Turntable turning an extra time shortly after being depowered.

### ISSUE THREAD

**Issue by ZazzyDoesStuff** [MehVahdJukaar/Supplementaries#45]
The turntable is consistently adding an extra turn ~2 seconds after being depowered. Works both on client and server on the newest version of the mod at the time of writing.

**Comment by MehVahdJukaar** [comment]
oh this is a pretty old bug. It's been like this for ages and I still have a todo saying to fix it but I guess I forgot. thanks for reminding me I'll get on trying to fix it once and for all

**Comment by MehVahdJukaar** [comment]
So took me a long time cause I wasn't sure how to address this. thing is that behavior is actually intended (other bug that I had in mind was another one after all). See when you power one, even with a short pulse it goes into its rotation phase that lasts an amount of ticks that depends on the power ir recieves and stays there until it had finished "rotating" a block. This was done to allow one to always perform single rotation by provinding a block with a 1 tick pulse no matter the signal strenght. It would  be easy to think of that rotation cooldown as an animation that starts playing once it gets powered and rotates the block when it finishes: I was considering adding such an animation (like creates one) that would make the whole thing a lot more intuitive but I opted against it since it would clip alot with nearby blocks. Instead I made its red light be on not for when it's being powered but for when it's rotating a block
