### ISSUE TITLE
[Suggestion] Add more blackboard color item tags

### ISSUE THREAD

**Issue by kingkuys2123** [MehVahdJukaar/Supplementaries#472]
**blackboard_yellow, blackboard_blue, blackboard_pink** etc.
to add support for other mods that adds more dyes and/or like colored chalks

**Comment by MehVahdJukaar** [comment]
I can do that but is it needed at the moment? Right now it uses forge dye tags instead, are there items that would classify as blackboard dyes but not as normal ones? Or maybe you want to remove some

**Comment by kingkuys2123** [comment]
I use Fabric version of Supplementaries by the way. 
I want to make this [mod's](https://www.curseforge.com/minecraft/mc-mods/chalk-fabric-colorful-addon) colored chalks to work with blackboards
no rush tho, it is not needed at the moment :)

**Comment by MehVahdJukaar** [comment]
Ah I see. On 1.18 we actually accidentally made double compat for that. I hardcoded some condition to check for items named chalks while mod author tagged their blocks using forge color tags so in both case they would work together. I guess I can add specific tags for more control just wrapping around forge ones since fabric doesn't have one either or has common one. I wish they would use the same convention... Had a while argument other day about forge adopting c namespace with its existing convention

**Comment by MehVahdJukaar** [comment]
ddeda

**Comment by kingkuys2123** [comment]
Thank you! :)
