### ISSUE TITLE
client Crash on 1.19.2 quilt/fabric

### ISSUE THREAD

**Issue by netcore10** [MehVahdJukaar/Supplementaries#513]
https://paste.atlauncher.com/view/a78eec18-1f84-44c2-a87f-5d59ebdb89f3

mc: 1.19.2

supplementaries: 2.2.48

quilt fapi 0.28 beta

**Comment by MehVahdJukaar** [comment]
issue with dramatic doors which is mixin into my classes

**Comment by netcore10** [comment]
version 2.2.46 works, was it a recent change?

**Comment by MehVahdJukaar** [comment]
i changed that class slightly to workaround an issue (not on my side) with better waterlogging mod
Ironically dramatic doors was ixing into my classes to do the exact same thing when imo it shouldnt have since it was patching another mod for yet another unrelated mod which was the real culprit to begin with. Adding a state to a block with mixin is never safe and should have at least accounted for it being added by a subclass by changing the state builder

**Comment by netcore10** [comment]
Fair, i added it to dramatic doors. Thanks for your input.

**Comment by Zarepheth** [comment]
https://github.com/Kitteh6660/DramaticDoors/issues/20
