### ISSUE TITLE
Crash out of no where on server

### ISSUE THREAD

**Issue by BugmanBugman** [MehVahdJukaar/Supplementaries#61]
[crash-2021-05-17_11.41.03-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/6495472/crash-2021-05-17_11.41.03-server.txt)

**Comment by MehVahdJukaar** [comment]
This one is pretty odd. Crash is due to an error of my part that was using a client side function on server side to print stuff on che console log. Thing is that only happened cause another error occurred (when generating way sings) thus the need to write stuff on the log. I fixed the printing thing so now should just fail silently as it's supposed to but I wonder what that first error was cause I've never had it. Are you using some custom world generation mod? I'll have to investigate more but it's probably an edge case of some sort

**Comment by BugmanBugman** [comment]
Yeah it happened in Terraforged
