### ISSUE TITLE
Supplementaries (supplementaries) has failed to load correctly

### ISSUE THREAD

**Issue by Neruwi** [MehVahdJukaar/Supplementaries#625]
Mod version: 1.19.2-2.3.14a
Forge version: Forge: 1.19.2 - 43.2.12
Starting the game gives me the error of the mod not loading correctly. The older version worked fine with Quark but now it's giving me this:
Exception message: java.lang.ClassNotFoundException: vazkii.quark.content.tools.item.PathfindersQuillItem

Full crash report if needed:
[crash-2023-05-30_00.14.02-fml.txt](https://github.com/MehVahdJukaar/Supplementaries/files/11595668/crash-2023-05-30_00.14.02-fml.txt)

**Comment by MehVahdJukaar** [comment]
Update quark. Keep all your mods updated it just takes a click of a button

**Comment by crafting-Aaron** [comment]
Pardon for commenting on a closed post but for anyone encountering a similar problem when using Valhelsia 5 modpack and wanted to manually update to Create 0.5.1 and its add-ons or compatibility mods. At first there was a texture problem with flax plants having a full black or white background on their texture. Updating Supplementaries then caused a crash and I skipped over this same exception message on the log thinking it was another mod causing the problem. I updated Quark and the problem is now fixed. 👍
 If using a modpack its better to be patient for an update as they would do the work for you but I really wanted those new elevators lol
