### ISSUE TITLE
 Supplementaries (supplementaries) encountered an error during the sided_setup event phase

### ISSUE THREAD

**Issue by Neruwi** [MehVahdJukaar/Supplementaries#626]
Mod version: 1.19.2-2.3.14a
Forge version: Forge: 1.19.2 - 43.2.12
Optifine version: OptiFine 1.19.2 HD U H9

All of my mods are the latest versions. 

Failure message: Supplementaries (supplementaries) encountered an error during the sided_setup event phase
		java.lang.NoSuchMethodError: 'void net.minecraft.client.renderer.block.model.BakedQuad.<init>(int[], int, net.minecraft.core.Direction, net.minecraft.client.renderer.texture.TextureAtlasSprite, boolean, boolean)'
	Exception message: java.lang.NoSuchMethodError: 'void net.minecraft.client.renderer.block.model.BakedQuad.<init>(int[], int, net.minecraft.core.Direction, net.minecraft.client.renderer.texture.TextureAtlasSprite, boolean, boolean)'

**Comment by MehVahdJukaar** [comment]
remove optifine, its not compatible with forge

**Comment by Neruwi** [comment]
> remove optifine, its not compatible with forge

It worked fine until I updated supplementaries. The older supplementaries file worked with all the mods I had.

**Comment by MehVahdJukaar** [comment]
thats because broken classes in java dont make you crash until they are loaded. i use a part of forge whch optifrick specificlaly break. they didnt bother to fix this for over a year now. I would neveer advise anybody to use optifine, it had a terrible reputation over the years od absolutely disregarding mods and foege itself brealing them in so many ways just for the way its built as a core mod instead of a proper forge mod

**Comment by Neruwi** [comment]
Ohhh thank you for the explanation! I'll remove optifine now

**Comment by Neruwi** [comment]
It worked!
