### ISSUE TITLE
Small feature request: Allow rope to be placed on the ground like Farmer's Delight rope

### ISSUE THREAD

**Issue by pm065** [MehVahdJukaar/Supplementaries#65]
Farmer's Delight rope can be used as a really nice border for fields:
![image](https://user-images.githubusercontent.com/81559564/119259356-d287d200-bbc5-11eb-8892-7b7b8062792f.png)
_10/10 good border_

But to prevent content overlap, I've disabled it in favour of Supplementaries rope, which I think looks nicer, but to use it as a border...
![image](https://user-images.githubusercontent.com/81559564/119259425-2db9c480-bbc6-11eb-95d6-c51dd3ed2321.png)
_Would not buy again._

...you have to do this. Would it be possible to make Supplementaries rope placeable on the ground?

**Comment by MehVahdJukaar** [comment]
well idk that would remove a feature imo since it would allow then to be placed anywhere and I like the fact that they can only exist when supported by other blocks. However I already thought of that thing you are trying to do and you can achieve a similar effect by placing a fence in each of the corner. Ropes can connect to the underside of blocks and to the sides of any fence block allowing for such fences to be made

**Comment by pm065** [comment]
Oh, I didn't know you could do that! Sorry!
