### ISSUE TITLE
Weird behavior with Harvest with ease

### ISSUE THREAD

**Issue by Nyphet** [MehVahdJukaar/Supplementaries#659]
Hello, I am the developer of [Harvest with ease](https://github.com/Nyphet/harvest-with-ease).  
I recently received a report ([issue 23](https://github.com/Nyphet/harvest-with-ease/issues/23#issuecomment-1593818012)) of a weird bug that happens when trying to right-click harvest a flax crop.

In my mod the right-click harvest of a tall crop follows this procedure:
1. `Block#getDroppedStacks` is called on the clicked block to get the correct drops for the harvest
2. The base block of the crop is located and reverted to age 0, while the above block is broken

This works fine when the right-clicked crop is the bottom part of the flax crop. However when the upper half of the flax crop is right-clicked, despite it breaking and reverting the whole crop to age 0, no drops are given.  
By checking the result of `Block#getDroppedStacks` called on the clicked half, when it's the bottom one it correctly gives the proper drops, while when it's the upper one the list of drops is empty.

Do you happen to have any insight on why this may be happening?  
Thank you

**Comment by MehVahdJukaar** [comment]
hi. i'm not eaxctly sure what you mean, its a bit late sorry. but basically flax is a 2 tall block and has a lower and an upper stage. upper stage is not ever meant to reach age 0 because at age 0 the plant does not have an upper stage (so half upper state 0-2 are unused blockstates). If your code handles that well that's good. ive seen some other mods do it well and some creating floating flax or using those unused double stages.
Anyways as a double plant flax only drops stuff from its lower stage. same behavior as vanilla double blocks

**Comment by Nyphet** [comment]
Okay, so everything is being handled well, but getting the drops from the upper stage won't work. I need to get the drops always from the lower stage.  
Thanks for the help!
