### ISSUE TITLE
Supplementaries & Fresh animations conflict

### ISSUE THREAD

**Issue by Fonntyy** [MehVahdJukaar/Supplementaries#706]
MC version: 1.19.2

Having Fresh Animations running on EMF and ETF, installing supplementaries breaks some entity textures and disables the new animations from from the Fresh Animations resource pack. Everything works when supplementaries is not installed, as I tested thoroughly. Not sure what might be the problem, but some of affected mobs are: underman (broken texture - no eyes, no new animations), horse (no new animations).

<img width="1440" alt="Screenshot 2023-07-15 at 9 57 52 PM" src="https://github.com/MehVahdJukaar/Supplementaries/assets/128201447/db1ae1fd-6061-49d2-b55e-a3f15ae55fc5">

**Comment by FontyCZ** [comment]
Toggling off underman_head features of supplementaries fixes the issue.

<img width="1440" alt="Screenshot 2023-07-16 at 1 08 31 PM" src="https://github.com/MehVahdJukaar/Supplementaries/assets/128201447/edee3e8d-5890-4586-ab45-b78ee9bf78a5">

**Comment by MehVahdJukaar** [comment]
im aware. ive got absolutely no idea how optifine does its hackery and these heads were not added in any intrusive way. only thing i do is get the enderman model and copy its head to be used there. I've specifically disabled that part when heads are off because i was told of this even tho following any logic this stuff shouldnt happen regardless. So in short not much i can do here

**Comment by Xelbayria** [comment]
I've added "details" so other people who have similar issues should find this info to be useful!. 
Is the issue resolved, if yes, then please close it.
