### ISSUE TITLE
Trinket Compat

### ISSUE THREAD

**Issue by JustWolter** [MehVahdJukaar/Supplementaries#710]
I recently tried to add key on our belt with my datapack and it worked but I can't open while it is in my belt because belt and others doesn't count as "inventory". Could you add this compat please??

(Or tell how can i do that if you dont have much time, thx)

![image](https://github.com/MehVahdJukaar/Supplementaries/assets/83448525/b0e2bc4a-0e1b-4d7a-95b3-bcec67192c76)
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/83448525/26a78ca3-d285-468b-a55d-2c4a9ab2e5e8)

**Comment by Ultimushadow** [comment]
Hey there, please check out my issue here: https://github.com/MehVahdJukaar/Supplementaries/issues/699
The Trinket slot is not a traditional inventory slot, so when the game looks for the key in your inventory, it doesn't see the Trinket slot. I added support within the mod to check for Trinkets for the Quiver and Key, and also Heavy Key is Supp Squared is added, so right now this issue is solved, ready to go in as soon as the mod author can check it out and get it in
In the meantime, here is Supplementaries 2.5.19 and SuppSquared 1.1.5 for 1.20.1 Fabric with the added functionality, assuming that is the version you're running
[Trinkets Supported Supplementaries.zip](https://github.com/MehVahdJukaar/Supplementaries/files/12079990/Trinkets.Supported.Supplementaries.zip)

**Comment by MehVahdJukaar** [comment]
added
