### ISSUE TITLE
[might be a bug?]SACK DUPE with <vanilla sand dupe principle>

### ISSUE THREAD

**Issue by DoctorIDD** [MehVahdJukaar/Supplementaries#738]
Mods : Only Supplementaries
Versions : Any version but include the sack
As we all know,sack performs as the sand.If the sack have been put above the end portal to let it be falling,it'll be two same sack in the other world.

**Comment by MehVahdJukaar** [comment]
Yeah if course it does, it's a vanilla bug you should bug moajng about it or if install a mod that fixes it which I believe exist at least for fabruc

**Comment by MehVahdJukaar** [comment]
can you link the mojang bug tracker of this bug?

**Comment by murao-kun** [comment]
The issue will be fixed with this mod installed. 
https://legacy.curseforge.com/minecraft/mc-mods/debugify-reforged

**Comment by yezhiyi9670** [comment]
I think we should at least include a warning about this so that server admins are aware of this. Normally sand duping is only used to dupe building blocks, anvils and dragon eggs, which does not have much impact on balance, but with sacks you can dupe virtually anything, which will definitely break the game if someone tries to exploit it.

**Comment by MehVahdJukaar** [comment]
well sand dupe affects all falling block entities, server owners should be aware of that. This is why its commo practice to add mods that fix vanilla bugs. It really baffles me this issue has not been fixed yet
