### ISSUE TITLE
conflict with quark

### ISSUE THREAD

**Issue by me6669** [MehVahdJukaar/Supplementaries#80]
having supplementaries installed with quark makes the placing blocks from dispenser functionality from quark not work

steps to reproduce:
-install quark and supplementaries(no other mods)
-place a block inside dispenser and power it
-doesnt work as quark intended

**Comment by MehVahdJukaar** [comment]
yes I have another issue opened for this and I'm working on it

**Comment by MehVahdJukaar** [comment]
they still won't work with stuff that I registered a behavior for (for example honey blocks since they can be placed in jars) this is due to how quark registers its things since it doesn't register the block placement behavior if it sees another already registered one instead of registering it and wrapping the old one like it do for example
