### ISSUE TITLE
Support for Sodium 0.5.8 (Fabric)

### ISSUE THREAD

**Issue by UnusedCactus** [MehVahdJukaar/Supplementaries#928]
On the newest versions of Sodium and Supplementaries on Fabric, Sodium will crash on startup and request a version of Supplementaries that does not exist (a version after 2.7.32). Indium also had this issue, however the newest version supports Sodium 0.5.8. Sodium does not request a newer version of Moonlight.
(Sorry for submitting this as a feature request when it more seems like a bug.)

**Comment by harithmf** [comment]
https://github.com/MehVahdJukaar/Supplementaries/issues/927#issuecomment-1936944985

**Comment by BowBoy1** [comment]
From what I'm seeing, Sodium forced an incompatibility with this mod because of how the forced indium compatibility was implemented.

Here's the relevant Sodium issue for the full context of the situation, since it doesn't seem that it was posted in #927 
https://github.com/CaffeineMC/sodium-fabric/issues/2303

**Comment by MehVahdJukaar** [comment]
Yes there's nothing I can do here. Do not report this stuff to me. Stuff is highly controversial I actually recommend using embeddium fabric
