### ISSUE TITLE
Fancy Ceiling Lanterns

### ISSUE THREAD

**Issue by ChloeDawn** [MehVahdJukaar/Supplementaries#942]
I would love for ceiling lanterns to have the same idle swaying animation as wall lanterns, and possibly swing physics too.

**Comment by MehVahdJukaar** [comment]
well the thing is that wouldnt really work as they would have to swing having a pivot point at their highest point where the chain touches the block above. This sees fine however one has to consider that those could be hung from other chanis too so swingin gonly there would look really bad. Moreover them not having preferred swiging side will make the physic that much harder to make, meaning it would need some major refactor

**Comment by ChloeDawn** [comment]
I personally feel that a subtle animation only at the pivot point of the lantern on a long chain would look fine but I understand if you disagree and wouldn't want it to behave that way in the mod. I also understand if you don't want or have the time to refactor the physics code to account for 4+ directions. I just felt like it was worth bringing up in a ticket just in case! Thanks for the detailed feedback ❤️

**Comment by MehVahdJukaar** [comment]
yeah thing is i used to have this very feature. Infact was the very reason copper lantern didnt have the chainy bit uptop. Only way to make the swing animation be bareable. With a normal lantern i would first have to replace existing ones with a tile entity or use major hacks i dnt even know (so already here would be impossible) and then make it so only the lower lantern bit animates as i cant just rotate the entire block as the point where 2 chains meet would otherwise break off and look really bad
