### ISSUE TITLE
[❓]: Sorry for spam, How to build? No response for 30 days.

### ISSUE THREAD

**Issue by SonicGamerEpisode55** [MehVahdJukaar/Supplementaries#996]
### Your Question

How to build the mod?

### Detail

Its probably related to the mod compats, I've fixed the moonlight issue, now it gives the error that quark, zeta and flywheel .pom was not found. Give me a detailed guide to build this mod.

Other mods, like cobblemon, wilderwild and create build fine without changing or downloading anything.

**Comment by MehVahdJukaar** [comment]
Because this is not an issue with the mod, it's trying to help you do something you want to do when you likely don't have enough experience in this stuff to begin with so it's even harder without having access to your intellij project and such. As I've said just grab all the dependencies from curse maven and replace the likes that are not from curse maven

**Comment by SonicGamerEpisode55** [comment]
Give me a DETAILED guide. The dependencies are not on curse maven.

**Comment by SonicGamerEpisode55** [comment]
how to do this

**Comment by SonicGamerEpisode55** [comment]
Sorry, I'm not really experienced, I'll wait for the time the cannon adds officially.

**Comment by MehVahdJukaar** [comment]
there's a reason why features arent realeased. They are not finished
